package com.geno1024.qqtangextractor.versions

import com.geno1024.qqtangextractor.*
import com.geno1024.qqtangextractor.ds.ResourceTree
import java.io.File

object QQTang5211
{
    operator fun invoke()
    {
        "/data/object.pkg" withIndex "/data/object.idx" decode "PKG"
        "/data/object/body" decodeFiles "IMG"
        "/data/object/bomb" decodeFiles "IMG"
        "/data/object/cap" decodeFiles "IMG"
        "/data/object/chatBg" decodeFiles "IMG"
        "/data/object/cladorn" decodeFiles "IMG"
        "/data/object/cloth" decodeFiles "IMG"
        "/data/object/face" decodeFiles "IMG"
        "/data/object/fhadorn" decodeFiles "IMG"
        "/data/object/flame" decodeFiles "IMG"
        "/data/object/foot" decodeFiles "IMG"
        "/data/object/hair" decodeFiles "IMG"
        "/data/object/head" decodeFiles "IMG"
        "/data/object/item" decodeFiles "IMG"
        "/data/object/leg" decodeFiles "IMG"
        "/data/object/light" decodeFiles "IMG"
        "/data/object/magic" decodeFiles "IMG"
        "/data/object/mapElem/bomb" decodeFiles "IMG"
        "/data/object/mapElem/box" decodeFiles "IMG"
        "/data/object/mapElem/bun" decodeFiles "IMG"
        "/data/object/mapElem/common" decodeFiles "IMG"
        "/data/object/mapElem/desert" decodeFiles "IMG"
        "/data/object/mapElem/exploration" decodeFiles "IMG"
        "/data/object/mapElem/field" decodeFiles "IMG"
        "/data/object/mapElem/machine" decodeFiles "IMG"
        "/data/object/mapElem/match" decodeFiles "IMG"
        "/data/object/mapElem/mine" decodeFiles "IMG"
        "/data/object/mapElem/pig" decodeFiles "IMG"
        "/data/object/mapElem/practice" decodeFiles "IMG"
        "/data/object/mapElem/pve" decodeFiles "IMG"
        "/data/object/mapElem/sculpture" decodeFiles "IMG"
        "/data/object/mapElem/snow" decodeFiles "IMG"
        "/data/object/mapElem/tank" decodeFiles "IMG"
        "/data/object/mapElem/town" decodeFiles "IMG"
        "/data/object/mapElem/treasure" decodeFiles "IMG"
        "/data/object/mapElem/water" decodeFiles "IMG"
        "/data/object/misc" decodeFiles "IMG"
        "/data/object/mouth" decodeFiles "IMG"
        "/data/object/npack" decodeFiles "IMG"
        "/data/object/pet" decodeFiles "IMG"
        "/data/object/thadorn" decodeFiles "IMG"
        "/data/object/ui/bg" decodeFiles "IMG"
        "/data/object/ui/chat" decodeFiles "IMG"
        "/data/object/ui/chatRoom" decodeFiles "IMG"
        "/data/object/ui/common" decodeFiles "IMG"
        "/data/object/ui/bg" decodeFiles "IMG"
        "/data/object/ui/cursor" decodeFiles "IMG"
        "/data/object/ui/deal" decodeFiles "IMG"
        "/data/object/ui/forge" decodeFiles "IMG"
        "/data/object/ui/game" decodeFiles "IMG"
        "/data/object/ui/game/record" decodeFiles "IMG"
        "/data/object/ui/guideBar" decodeFiles "IMG"
        "/data/object/ui/guideBar/friend" decodeFiles "IMG"
        "/data/object/ui/guideBar/kin" decodeFiles "IMG"
        "/data/object/ui/guideBar/player" decodeFiles "IMG"
        "/data/object/ui/kinTotem" decodeFiles "IMG"
        "/data/object/ui/level/medal" decodeFiles "IMG"
        "/data/object/ui/level/tie" decodeFiles "IMG"
        "/data/object/ui/login" decodeFiles "IMG"
        "/data/object/ui/map/midIcon" decodeFiles "IMG"
        "/data/object/ui/marriage" decodeFiles "IMG"
        "/data/object/ui/marriage/bg" decodeFiles "IMG"
        "/data/object/ui/marriage/marriageLevel" decodeFiles "IMG"
        "/data/object/ui/marriage/priest" decodeFiles "IMG"
        "/data/object/ui/marriage/ring" decodeFiles "IMG"
        "/data/object/ui/pet" decodeFiles "IMG"
        "/data/object/ui/record" decodeFiles "IMG"
        "/data/object/ui/room" decodeFiles "IMG"
        "/data/object/ui/room/char" decodeFiles "IMG"
        "/data/object/ui/room/map" decodeFiles "IMG"
        "/data/object/ui/selRoom" decodeFiles "IMG"
        "/data/object/ui/selRoom/map" decodeFiles "IMG"
        "/data/object/ui/selSect" decodeFiles "IMG"
        "/data/object/ui/shop" decodeFiles "IMG"
        "/data/object/ui/shop/breakEgg" decodeFiles "IMG"
        "/data/object/ui/shop/luckyStar" decodeFiles "IMG"
        "/data/object/ui/shop/rolename" decodeFiles "IMG"
        "/data/object/ui/shop/secrecyValidate" decodeFiles "IMG"
        "/data/object/ui/charIcon" decodeFiles "IMG"
        "/data/object/ui/lightIcon" decodeFiles "IMG"
        "/data/object/ui/luckyStar" decodeFiles "IMG"
        "/data/object/ui/rolename" decodeFiles "IMG"
        "/data/object/ui/secrecyValidate" decodeFiles "IMG"
        "/data/object/ui/shop" decodeFiles "IMG"
        "/data/object/ui/shop/charIcon" decodeFiles "IMG"
        "/data/object/ui/shop/lightIcon" decodeFiles "IMG"
        "/data/object/ui/shop/ware" decodeFiles "IMG"
        "/data/object/ui/shop/wareAttr" decodeFiles "IMG"
        "/data/object/ui/storage" decodeFiles "IMG"
        "/data/object/ui/task" decodeFiles "IMG"
        "/data/object/ui/web" decodeFiles "IMG"
        "/map" decodeFiles "IMG"
        "/map/icon" decodeFiles "IMG"
        "/music" copyTo "/music"
        "/object/namecard" decodeFiles "IMG"
        "/object/ui/cursor/fight.gsa" decode "IMG"
        "/object/ui/login/img_logo.img" decode "IMG"
        "/res/uiRes/face" decodeFiles "IMG"
        "/res/uiRes/face/faces" decodeFiles "IMG"
        "/res/uiRes/face/faces/member" decodeFiles "IMG"
        "/res/uiRes/game" decodeFiles "IMG"
        "/res/uiRes/gameChat" decodeFiles "IMG"
        "/res/uiRes/icon/chatBg" decodeFiles "IMG"
        "/res/uiRes/icon/item" decodeFiles "IMG"
        "/res/uiRes/icon/light" decodeFiles "IMG"
        "/res/uiRes/icon/namecard" decodeFiles "IMG"
        "/res/uiRes/icon/npcIcon" decodeFiles "IMG"
        "/res/uiRes/icon/pet" decodeFiles "IMG"
        "/res/uiRes/icon/petItem" decodeFiles "IMG"
        "/res/uiRes/icon/platform" decodeFiles "IMG"
//        "/res/uiRes/number" decodeFiles "OTF"
        "/res/uiRes/selRoom" decodeFiles "IMG"
        "/res/uiRes/selRoom/icon" decodeFiles "IMG"
        "/res/uiRes/selRoom/mapFilter" decodeFiles "IMG"
        "/res/uiRes/selRoom/recorder" decodeFiles "IMG"
//        "/res/uiRes/selRoom/room/num_player.img" decode "OTF"
        "/res/uiRes/selSect" decodeFiles "IMG"
        "/res/uiRes/shop" decodeFiles "IMG"
        "/sound" copyTo "/sound"
        File("${Settings.version}/README.md").writeText(ResourceTree.toTreeDiagram())
    }
}
