name: Pack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pack QQTang5.2_Beta1Build1
        run:
          zip -r QQTang5.2_Beta1Build1.zip QQTang5.2_Beta1Build1
      - name: Output artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            QQTang5.2_Beta1Build1.zip
